<?php exit;
'well_publish' => '投稿',
'well_publish_enable_tag' => '标签填写',
'well_publish_enable_publish_limit_tips' => '投稿数量限制，0不限，用户投稿未审核，达到设置数量，将限制投稿，审核后可继续投稿。',
'well_publish_publish_limit_tips' => '投稿已达到 {n} 数量限制，审核后可继续投稿。',
'well_publish_enable_comment_limit_tips' => '评论数量限制，0不限，用户评论未审核，达到设置数量，将限制回复，审核后可继续评论。',
'well_publish_comment_limit_tips' => '评论已达到 {n} 数量限制，审核后可继续评论。',
'well_publish_reject_limit_tips' => '退稿已达到 {n} 数量限制，需要清理退稿。',
'well_publish_enable_reject_limit_tips' => '退稿数量限制，0不限，用户退稿达到设置数量，将限制投稿，需用户清理后方可投稿。',
'well_publish_reject' => '退稿',
'well_publish_verified' => '通过',
'well_publish_not_open' => '未开放写文章',
'well_publish_article' => '写文章',
'well_publish_edit' => '编辑文章',
'well_publish_verify' => '投稿审核',
'well_comment_verify' => '评论审核',
'well_verify_content' => '审核内容',
'well_latest_news' => '动态',
'well_publish_pending_thread' => '待审主题',
'well_publish_verify_thread' => '审核主题',
'well_publish_pending_comment' => '待审评论',
'well_publish_verify_comment' => '审核评论',
'well_publish_allowthumbnail' => '发主图',
'well_publish_allowbrief' => '写简介',
'well_publish_allowkeywords' => '写关键词',
'well_publish_allowdescription' => '写描述',
?>