<?php exit;
'well_publish' => '投稿',
'well_publish_enable_tag' => '標籤填寫',
'well_publish_enable_publish_limit_tips' => '投稿數量限制，0不限，用戶投稿未審核，達到設置數量，將限制投稿，審核後可繼續投稿。',
'well_publish_publish_limit_tips' => '投稿已達到 {n} 數量限制，審核後可繼續投稿。',
'well_publish_enable_comment_limit_tips' => '評論數量限制，0不限，用戶評論未審核，達到設置數量，將限制回复，審核後可繼續評論。',
'well_publish_comment_limit_tips' => '評論已達到 {n} 數量限制，審核後可繼續評論。',
'well_publish_reject_limit_tips' => '退稿已達到 {n} 數量限制，需要清理退稿。',
'well_publish_enable_reject_limit_tips' => '退稿數量限制，0不限，用戶退稿達到設置數量，將限制投稿，需用戶清理後方可投稿。',
'well_publish_reject' => '退稿',
'well_publish_verified' => '通過',
'well_publish_not_open' => '未開放寫文章',
'well_publish_article' => '寫文章',
'well_publish_edit' => '編輯文章',
'well_publish_verify' => '投稿審核',
'well_comment_verify' => '評論審核',
'well_verify_content' => '審核內容',
'well_latest_news' => '動態',
'well_publish_pending_thread' => '待審主題',
'well_publish_verify_thread' => '審核主題',
'well_publish_pending_comment' => '待審評論',
'well_publish_verify_comment' => '審核評論',
'well_publish_allowthumbnail' => '發主圖',
'well_publish_allowbrief' => '寫簡介',
'well_publish_allowkeywords' => '寫關鍵詞',
'well_publish_allowdescription' => '寫描述',
?>