<?php exit;
'well_publish' => 'Contribute',
'well_publish_enable_tag' => 'Add tag',
'well_publish_enable_publish_limit_tips' => 'The number of submissions is limited. 0 is not limited. If the number of user submissions has not been reviewed, the submission will be restricted, submission can be continued after review.',
'well_publish_publish_limit_tips' => 'The number of submissions has reached the limit of {n}. You can continue to submit after review.',
'well_publish_enable_comment_limit_tips' => 'The number of comments is limited. 0 is not limited. User comments are not reviewed. If the set number is reached, comment will be limited, and comments can be continued after review.',
'well_publish_comment_limit_tips' => 'The number of comments has reached the limit of {n}. You can continue to comment after review.',
'well_publish_reject_limit_tips' => 'The number of rejected manuscripts has reached the {n} limit, and the rejected manuscripts need to be cleaned up.',
'well_publish_enable_reject_limit_tips' => 'The number of rejected manuscripts is limited. 0 is not limited. If the number of rejected manuscripts is reached, the user will be restricted to submit manuscripts, and the manuscript can be submitted after the user clears it.',
'well_publish_reject' => 'Reject',
'well_publish_verified' => 'Verified',
'well_publish_not_open' => 'Not open',
'well_publish_article' => 'Contribute',
'well_publish_edit' => 'Edit',
'well_publish_verify' => 'Contribution review',
'well_comment_verify' => 'Comment review',
'well_verify_content' => 'Review content',
'well_latest_news' => 'Latest',
'well_publish_pending_thread' => 'Pending article',
'well_publish_verify_thread' => 'Verify article',
'well_publish_pending_comment' => 'Pending comment',
'well_publish_verify_comment' => 'Verify comment',
'well_publish_allowthumbnail' => 'Allow Thumbnail',
'well_publish_allowbrief' => 'Allow Brief',
'well_publish_allowkeywords' => 'Keywords',
'well_publish_allowdescription' => 'Description',
?>